"""
Django settings for Restful_Project project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'am5)jx1f#&=ae1di)+$xt*^+mm1j5fcwdd!-2fv108=qtz02aq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'luffy.apps.LuffyConfig',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'luffy.middlewares.rbac.LoginMiddleware',
]

ROOT_URLCONF = 'Restful_Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Restful_Project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'luffycity',
        'USER':'root',
        'PASSWORD':'luominwen',
        'HOST':'localhost',
        'PORT':'3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

#中间件查询cookie
COOKIES_KEY='token'

STATIC_URL = '/static/'


REST_FRAMEWORK = {
        'UNAUTHENTICATED_USER': None, #默认user
        'UNAUTHENTICATED_TOKEN': None, # 默认auth
        #认证
        "DEFAULT_AUTHENTICATION_CLASSES": [
            # "luffy.views.MyAuthentication",
        ],
        #权限
        # "DEFAULT_PERMISSION_CLASSES": [
        #     "app01.utils.TestPermission",
        #     ],
        #节流
        # 'DEFAULT_THROTTLE_RATES':{
        #     'myscope_anon':'5/minute',
        #     'myscope_user':'10/minute',
        # },
        #版本
        # 'DEFAULT_VERSION':'v1',
        # 'ALLOWED_VERSIONS':'[v1,v2]',
        # 'VERSION_PARAM':'version',
        # 'DEFAULT_VERSIONING_CLASS':"rest_framework.versioning.QueryParameterVersioning",
        # 'DEFAULT_VERSIONING_CLASS':"rest_framework.versioning.URLPathVersioning",

        #解析器 parser
        # 'DEFAULT_PARSER_CLASSES':[
        #     'rest_framework.parsers.JSONParser',
        #     'rest_framework.parsers.FormParser',
        # ],
        #每页默认显示几条数据
        # 'PAGE_SIZE':1,
    }